[package]
name = "ropenbci"
version = "2021.8.23"
authors = ["Matthew Stone <dev@mattstone.io>"]
edition = "2018"

[dependencies]
log = "0.4"
serialport = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ascii = "1.0"
